"""
EvaporationOOP_testing.py
=========================
Regression test suite comparing EvaporatorSet (and PreEvaporator) OOP results
against the reference outputs stored in 'evaporator_cases_all.xlsx', which were
generated by the original functional solve_set() program (evaporator (1).py).

All 13 cases use the same juice and steam conditions unless noted:
  juice_in      : 100 tph, brix=12, temp=225 degF
  syrup target  : brix=60
  exhaust steam : 20 psig (34.696 psia), saturated
  last effect   : 26 in Hg vacuum (~1.925 psia)
  inj water     : 95 degF in / 120 degF out
  liquid level  : 2 ft
  dessin const  : 18000

Cases 1-3   : 3-effect sets, varying areas and vapor bleeds
Cases 4-5   : pre-evaporator + 3-effect set
Cases 6-9   : 4-effect sets, varying areas and vapor bleeds
Case  10    : pre-evaporator + 4-effect set
Cases 11-13 : 5-effect sets, varying areas and vapor bleeds

Pass criterion: all key outputs within TOLERANCE_PCT of the reference value.
"""

import sys, warnings, contextlib, io
warnings.filterwarnings("ignore")
sys.path.insert(0, r"c:\Users\ceaves\OneDrive - St. Mary Sugar\MaterialEnergypy")
import time
from SugarStream import SugarStream
from SteamStream import EvaporatorSteam
from EvaporatorSet import EvaporatorSet
from PreEvaporator import PreEvaporator
from evaporator_functions import convert_psig_to_psia, convert_inHg_vacuum_to_psia


start_time = time.time()

# ── Tolerance ─────────────────────────────────────────────────────────────────
TOLERANCE_PCT = 0.01   # 0.01% — 10x tighter than observed accuracy

# ── Shared constants ──────────────────────────────────────────────────────────
SUPPLY_PSIA  = convert_psig_to_psia(20)        # 34.696 psia
LAST_PSIA    = convert_inHg_vacuum_to_psia(26) # ~1.925 psia
JUICE_LB_HR  = 100 * 2000                      # 200,000 lb/hr
DESSIN       = 18000
LEVEL_FT     = 2
TARGET_BRIX  = 60

# ── Case definitions ──────────────────────────────────────────────────────────
# Each entry: (case_number, description, inputs_dict, reference_dict)
#
# inputs keys for set-only cases:
#   areas       : list of heating surface areas ft2 per effect
#   bleeds      : list of vapor bleeds lb/hr per effect
#
# inputs keys for pre-evap cases (in addition):
#   pre_bleed   : vapor bleed on pre-evap lb/hr  (fixed evaporation)
#   pre_hs      : heating surface of pre-evap ft2
#
# reference keys:
#   set_exh     : exhaust required by the set lb/hr
#   u_ratio     : converged U_calc/U_dessin ratio (uniform across effects)
#   pre_exh     : pre-evap exhaust lb/hr (pre-evap cases only)
#   pre_vap_p   : pre-evap vapor pressure psia (pre-evap cases only)

CASES = [
    # ── 3-effect sets ────────────────────────────────────────────────────────
    (1, "3-eff, no bleeds",
     {"areas": [4800, 4800, 4800], "bleeds": [0, 0, 0]},
     {"set_exh": 53825.59, "u_ratio": 0.904656}),

    (2, "3-eff, bleed eff-1 (17.626 tph)",
     {"areas": [6700, 3900, 3900], "bleeds": [17.626*2000, 0, 0]},
     {"set_exh": 77925.32, "u_ratio": 0.915604}),

    (3, "3-eff, bleed eff-1 (31.68 tph)",
     {"areas": [8800, 3100, 3100], "bleeds": [31.68*2000, 0, 0]},
     {"set_exh": 97299.95, "u_ratio": 0.915153}),

    # ── pre-evap + 3-effect sets ─────────────────────────────────────────────
    (4, "pre-evap (17.626 tph bleed) + 3-eff, no bleeds",
     {"pre_bleed": 17.626*2000, "pre_hs": 3300,
      "areas": [3800, 3800, 3800], "bleeds": [0, 0, 0]},
     {"pre_exh": 38696.74, "pre_vap_p": 24.201729,
      "set_exh": 39457.75, "u_ratio": 0.900765}),

    (5, "pre-evap (31.68 tph bleed) + 3-eff, no bleeds",
     {"pre_bleed": 31.68*2000, "pre_hs": 5900,
      "areas": [3000, 3000, 3000], "bleeds": [0, 0, 0]},
     {"pre_exh": 67194.06, "pre_vap_p": 24.148223,
      "set_exh": 30279.44, "u_ratio": 0.910559}),

    # ── 4-effect sets ────────────────────────────────────────────────────────
    (6, "4-eff, no bleeds",
     {"areas": [5100, 5100, 5100, 5100], "bleeds": [0, 0, 0, 0]},
     {"set_exh": 40814.61, "u_ratio": 0.886062}),

    (7, "4-eff, bleed eff-1 (17.626 tph)",
     {"areas": [5900, 4600, 4600, 4600], "bleeds": [17.626*2000, 0, 0, 0]},
     {"set_exh": 67270.85, "u_ratio": 0.910296}),

    (8, "4-eff, bleed eff-1 (31.68 tph)",
     {"areas": [8200, 3650, 3650, 3650], "bleeds": [31.68*2000, 0, 0, 0]},
     {"set_exh": 89097.94, "u_ratio": 0.919103}),

    (9, "4-eff, bleeds eff-1 & eff-2",
     {"areas": [7750, 6250, 3125, 3125], "bleeds": [20.481*2000, 11.06*2000, 0, 0]},
     {"set_exh": 83388.80, "u_ratio": 0.901590}),

    # ── pre-evap + 4-effect set ──────────────────────────────────────────────
    (10, "pre-evap (31.68 tph bleed) + 4-eff, no bleeds",
     {"pre_bleed": 31.68*2000, "pre_hs": 5900,
      "areas": [3200, 3200, 3200, 3200], "bleeds": [0, 0, 0, 0]},
     {"pre_exh": 67194.06, "pre_vap_p": 24.148223,
      "set_exh": 22528.28, "u_ratio": 0.901601}),

    # ── 5-effect sets ────────────────────────────────────────────────────────
    (11, "5-eff, no bleeds",
     {"areas": [5350, 5350, 5350, 5350, 5350], "bleeds": [0, 0, 0, 0, 0]},
     {"set_exh": 33038.71, "u_ratio": 0.881135}),

    (12, "5-eff, bleeds eff-1 & eff-2",
     {"areas": [13700, 8150, 3600, 3600, 3600], "bleeds": [20.481*2000, 11.0945*2000, 0, 0, 0]},
     {"set_exh": 80483.08, "u_ratio": 0.759860}),

    (13, "5-eff, bleeds eff-1, eff-2, eff-3",
     {"areas": [10750, 7200, 6100, 2100, 2100], "bleeds": [16.012*2000, 4.461*2000, 11.003*2000, 0, 0]},
     {"set_exh": 74219.49, "u_ratio": 0.908546}),
]


# ── Helpers ───────────────────────────────────────────────────────────────────

def _pct_diff(oop, ref):
    return (oop - ref) / ref * 100 if ref != 0 else float("inf")

def _pass(pct):
    return abs(pct) <= TOLERANCE_PCT

def _check(label, oop_val, ref_val, results):
    pct = _pct_diff(oop_val, ref_val)
    ok  = _pass(pct)
    results.append((label, ref_val, oop_val, pct, ok))
    return ok

def _build_juice():
    return SugarStream(
        brix=12, purity=90, flow_lb_per_hr=JUICE_LB_HR,
        temp_deg_F=225, pressure_psia=SUPPLY_PSIA, level_ft=0
    )

def _build_steam():
    return EvaporatorSteam(P_psia=SUPPLY_PSIA, flow_lb_per_hr=0)

def _run_set(juice_in, areas, bleeds):
    steam = _build_steam()
    with contextlib.redirect_stdout(io.StringIO()):
        es = EvaporatorSet(
            juice_in=juice_in, supply_steam=steam,
            last_effect_pressure_psia=LAST_PSIA, target_brix_out=TARGET_BRIX,
            effect_areas_ft2=areas, vapor_bleeds=bleeds,
            dessin_coefficient=DESSIN, liquid_level_ft=LEVEL_FT,
        )
        es.adjust_pressure_profile()
    u_ratios = [e.U_ratio for e in es.evaporator_list]
    avg_u    = sum(u_ratios) / len(u_ratios)
    last_brix = es.evaporator_list[-1].juice_side_out.brix
    return es.supply_steam.flow_lb_per_hr, avg_u, last_brix


# ── Run all cases ─────────────────────────────────────────────────────────────

def run_tests(verbose=True):
    total_checks = 0
    total_pass   = 0
    case_results = []

    for case_num, desc, inputs, ref in CASES:
        results = []   # (label, ref, oop, pct, ok)
        has_pre = "pre_bleed" in inputs

        if has_pre:
            juice_raw = _build_juice()
            with contextlib.redirect_stdout(io.StringIO()):
                pre = PreEvaporator(
                    juice_in=juice_raw,
                    supply_steam=_build_steam(),
                    vapor_bleed_lb_per_hr=inputs["pre_bleed"],
                    area_ft2=inputs["pre_hs"],
                    liquid_level_ft=LEVEL_FT,
                    dessin_coefficient=DESSIN,
                )
            _check("Pre exh (lb/hr)",   pre.exhaust_required_lb_per_hr, ref["pre_exh"],   results)
            _check("Pre vap P (psia)",  pre.vapor_pressure_psia,        ref["pre_vap_p"], results)
            juice_for_set = pre.juice_out
        else:
            juice_for_set = _build_juice()

        set_exh, avg_u, last_brix = _run_set(juice_for_set, inputs["areas"], inputs["bleeds"])

        _check("Set exh (lb/hr)", set_exh,   ref["set_exh"],  results)
        _check("U ratio",         avg_u,      ref["u_ratio"],  results)
        _check("Brix out",        last_brix,  TARGET_BRIX,     results)

        n_pass = sum(1 for *_, ok in results if ok)
        n_tot  = len(results)
        total_checks += n_tot
        total_pass   += n_pass
        case_results.append((case_num, desc, results, n_pass, n_tot))

    # ── Print results ─────────────────────────────────────────────────────────
    sep = "-" * 88
    print()
    print("=" * 88)
    print("  EvaporationOOP Regression Test — all cases vs. evaporator_cases_all.xlsx")
    print(f"  Tolerance: {TOLERANCE_PCT}%   |   Juice: 100 tph, brix 12 -> syrup brix 60")
    print("=" * 88)

    for case_num, desc, results, n_pass, n_tot in case_results:
        status = "PASS" if n_pass == n_tot else "FAIL"
        print(f"\nCase {case_num:>2}: {desc}")
        print(f"  Status: {status} ({n_pass}/{n_tot} checks)")
        if verbose:
            print(f"  {'Metric':<22} {'Reference':>15} {'OOP':>15} {'Diff %':>9}  {'':>5}")
            print(f"  {sep[:75]}")
            for label, ref_val, oop_val, pct, ok in results:
                flag = "OK" if ok else "FAIL <--"
                print(f"  {label:<22} {ref_val:>15,.4f} {oop_val:>15,.4f} {pct:>8.4f}%  {flag}")

    print()
    print("=" * 88)
    overall = "ALL PASS" if total_pass == total_checks else f"{total_checks - total_pass} FAILURES"
    print(f"  OVERALL: {overall}  ({total_pass}/{total_checks} checks passed)")
    print("=" * 88)
    print()

    end_time = time.time()

    solve_time = end_time - start_time

    print(f"Time to run testing: {solve_time:.6f} seconds")


    return total_pass == total_checks


if __name__ == "__main__":
    all_passed = run_tests(verbose=True)
    sys.exit(0 if all_passed else 1)

